services:
  database:
    container_name: "postgres-dev"
    image: "postgres:16.0-alpine3.18"
    env_file:
      - ../.env.development #Acessando o password do banco de dados através do arquivo .env (onde estão as variáveis de ambiente).
    ports:
      - "5432:5432"
