name: Linting

on: pull_request # Quando alguém criar um pull_request rode os jobs abaixo;

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest # define o SO que rodará o workflow
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/hydrogen"

      - run: npm ci # Faz as intalações do package-lock.json assim como o `npm install`, no entanto ele não às atualiza!

      - run: npm run lint:prettier:check

  eslint:
    name: Eslint
    runs-on: ubuntu-latest # define o SO que rodará o workflow
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/hydrogen"

      - run: npm ci # Faz as intalações do package-lock.json assim como o `npm install`, no entanto ele não às atualiza!

      - run: npm run lint:eslint:check

  commitlint:
    name: Commitlint
    runs-on: ubuntu-latest # define o SO que rodará o workflow
    steps:
      - uses: actions/checkout@v4
        with:
        fetch-depth: 0 # Necessário para que o commitlint consiga comparar os commits do PR

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/hydrogen"

      - run: npm ci # Faz as intalações do package-lock.json assim como o `npm install`, no entanto ele não às atualiza!

      - run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
